[build]
  command = "npm ci --prefix apps/platform1 || npm install --prefix apps/platform1 && npm run --prefix apps/platform1 build"
  publish = "apps/platform1/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
