[build]
base = "apps/platform1"
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "18"
NEXT_TELEMETRY_DISABLED = "1"

[functions]
node_bundler = "esbuild"

a[[plugins]]
package = "@netlify/plugin-nextjs"
